id: P006758
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG05
  title: སེ་ར་དགོན་པའི་གནས་བཤད་དང་རྗེ་བྱམས་ཆེན་ཆོས་རྗེའི་རྣམ་ཐར
  author: ''
  volumes:
    6c5f67bfb5704fd19640f59092afc346:
      image_group_id: I1GS65486
      title: ''
      volume_number: 1
      total_pages: 75
      base_file: v001.txt
