id: P006758
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:21:22.275298
source_metadata:
  id: bdr:W00KG05
  title: སེ་ར་དགོན་པའི་གནས་བཤད་དང་རྗེ་བྱམས་ཆེན་ཆོས་རྗེའི་རྣམ་ཐར
  author: ''
  volumes:
    6c5f67bfb5704fd19640f59092afc346:
      image_group_id: I1GS65486
      title: ''
      volume_number: 1
      total_pages: 75
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
